"""curriculum-mcp — a standalone MCP server over a KSE prep-track concept graph
(Calculus / Linear Algebra / Machine Learning / Probability essentials).

Runs as its own process, independent of any agent:
    python -m mcp_servers.curriculum_mcp.server

Data: output/dataset/concept_graph.json (generated by conceptgraph, see repo
root) + course_metadata.json (hand-transcribed ECTS/prerequisite facts). Both
load once at startup — no network calls happen while serving tool requests.
"""
from __future__ import annotations

from typing import Annotated

from mcp.server.mcpserver import MCPServer
from mcp.server.mcpserver.exceptions import ToolError
from pydantic import Field

from . import graph_store
from .graph_store import UnknownCourseError
from .models import (
    Conflict,
    CompareCoursesOutput,
    DetectPlanConflictsOutput,
    ExternalPrerequisiteNote,
    PlannedCourse,
    PrerequisiteViolation,
    RelatedConceptPair,
    SuggestSubstitutionOutput,
    ValidateStudyPlanOutput,
)

server = MCPServer(
    name="curriculum-mcp",
    version="0.1.0",
    instructions=(
        "Domain operations over a 4-course prep-track concept graph (Calculus, "
        "Linear Algebra, Machine Learning, Probability essentials): study-plan "
        "validation against prerequisites and ECTS budget, term-schedule conflict "
        "detection, course-waiver feasibility from prior knowledge, and course "
        "comparison. Course codes: CALC, LINALG, ML, PROB."
    ),
)


def _course_or_error(code: str) -> str:
    try:
        return graph_store.get_graph().course(code).code
    except UnknownCourseError:
        known = ", ".join(graph_store.get_graph().known_course_codes())
        raise ToolError(f"unknown_course_code: {code!r} is not one of the known courses ({known})") from None


@server.tool()
def validate_study_plan(
    target_courses: Annotated[list[str], Field(min_length=1,
        description="Course codes the student wants to take, e.g. ['ML', 'PROB'].")],
    completed_courses: Annotated[list[str], Field(
        description="Course codes the student has already completed.")] = [],
    max_total_ects: Annotated[int | None, Field(gt=0,
        description="Optional ECTS budget for target_courses (excluding already-completed ones).")] = None,
) -> ValidateStudyPlanOutput:
    """Validate a set of target courses against known prerequisites and an optional ECTS budget.

    Checks two things this dataset can actually support: (1) internal
    prerequisites among CALC/LINALG/ML/PROB themselves (per their own syllabi,
    currently none of the four requires another — see course_metadata.json),
    and (2) each target course's OWN external prerequisites, which reference
    courses outside this dataset and so are surfaced as advisory notes rather
    than verified. Use before enrolling in a term to catch budget overruns or
    an out-of-order plan.
    """
    g = graph_store.get_graph()
    targets = [_course_or_error(c) for c in target_courses]
    completed = {_course_or_error(c) for c in completed_courses}

    order, cycle = g.topological_order(targets)
    violations = [
        PrerequisiteViolation(course_code=c, missing_prerequisite_course=p)
        for c in targets
        for p in g.courses[c].internal_prerequisites
        if p not in completed and p not in targets
    ]
    if cycle:
        violations += [PrerequisiteViolation(course_code=c, missing_prerequisite_course="<cycle>") for c in cycle]

    notes = [
        ExternalPrerequisiteNote(course_code=c, note=note)
        for c in targets if c not in completed
        for note in g.courses[c].external_prerequisites
    ]

    total_ects = sum(g.courses[c].ects for c in targets if c not in completed)
    over_budget = max_total_ects is not None and total_ects > max_total_ects

    return ValidateStudyPlanOutput(
        valid=not violations and not over_budget,
        total_ects=total_ects,
        over_budget=over_budget,
        internal_prerequisite_violations=violations,
        external_prerequisite_notes=notes,
        recommended_order=order + cycle,
    )


@server.tool()
def detect_plan_conflicts(
    plan: Annotated[list[PlannedCourse], Field(min_length=1,
        description="Each course the student plans to take, with the term/semester they'd take it in.")],
    max_ects_per_term: Annotated[int, Field(gt=0,
        description="Per-term ECTS load cap used to flag overload.")] = 15,
) -> DetectPlanConflictsOutput:
    """Check a term-by-term schedule for credit overload, duplicate enrollment, and prerequisite-order conflicts.

    Unlike validate_study_plan (which checks WHAT to take), this checks WHEN:
    it groups the plan by term, flags any term whose combined ECTS exceeds
    max_ects_per_term, flags a course scheduled twice, and — for any internal
    prerequisite this dataset does record — flags a course scheduled no later
    than the term of a course it depends on.
    """
    g = graph_store.get_graph()
    for pc in plan:
        _course_or_error(pc.course_code)

    conflicts: list[Conflict] = []
    seen_courses: dict[str, int] = {}
    term_of: dict[str, int] = {}
    ects_by_term: dict[int, int] = {}
    for pc in plan:
        code = pc.course_code.upper()
        if code in seen_courses:
            conflicts.append(Conflict(type="duplicate_course", term=None, courses=[code],
                detail=f"{code} appears in both term {seen_courses[code]} and term {pc.term}."))
        seen_courses[code] = pc.term
        term_of[code] = pc.term
        ects_by_term[pc.term] = ects_by_term.get(pc.term, 0) + g.courses[code].ects

    for term, ects in sorted(ects_by_term.items()):
        if ects > max_ects_per_term:
            term_courses = [c for c, t in term_of.items() if t == term]
            conflicts.append(Conflict(type="credit_overload", term=term, courses=term_courses,
                detail=f"term {term} totals {ects} ECTS, over the {max_ects_per_term} cap."))

    for code, term in term_of.items():
        for prereq in g.courses[code].internal_prerequisites:
            if prereq in term_of and term_of[prereq] >= term:
                conflicts.append(Conflict(type="prerequisite_order", term=term, courses=[prereq, code],
                    detail=f"{code} (term {term}) requires {prereq} (term {term_of[prereq]}) to come earlier."))

    return DetectPlanConflictsOutput(
        ok=not conflicts, conflicts=conflicts,
        ects_by_term={str(t): e for t, e in sorted(ects_by_term.items())},
    )


@server.tool()
def suggest_substitution(
    course_code: Annotated[str, Field(description="Course to evaluate for a waiver, e.g. 'PROB'.")],
    known_concepts: Annotated[list[str], Field(min_length=1,
        description="Free-text concept names the student already knows, from prior education.")],
    max_residual_concepts: Annotated[int, Field(ge=0,
        description="Largest self-study gap still acceptable to call the course waivable.")] = 5,
) -> SuggestSubstitutionOutput:
    """Evaluate whether a course can be waived in favor of self-study, given concepts the student already knows.

    Matches each known_concepts entry against the course's actual concept
    names (normalized word-overlap, since these are free-text and course
    concepts don't share a controlled vocabulary across courses in this
    dataset). Returns the covered/residual split and whether the residual
    gap is small enough to approve a waiver under max_residual_concepts —
    the "credit constraint": the alternative to a waiver is spending the
    course's full ECTS load, so this is what validate_study_plan's budget
    check would act on next.
    """
    course = graph_store.get_graph().course(_course_or_error(course_code))
    covered, residual = graph_store.get_graph().match_known_concepts(course.code, known_concepts)
    waivable = len(residual) <= max_residual_concepts
    note = (f"{len(residual)} concept(s) not recognized among the {len(known_concepts)} known_concepts given; "
            + ("waivable within the residual-gap limit." if waivable
               else f"exceeds the max_residual_concepts={max_residual_concepts} limit."))
    return SuggestSubstitutionOutput(
        course_code=course.code, ects=course.ects, total_concepts=len(course.concepts),
        covered_concepts=covered, residual_concepts=residual, residual_count=len(residual),
        waivable=waivable, note=note,
    )


@server.tool()
def compare_courses(
    course_a: Annotated[str, Field(description="First course code, e.g. 'LINALG'.")],
    course_b: Annotated[str, Field(description="Second course code, e.g. 'PROB'.")],
) -> CompareCoursesOutput:
    """Compare two courses: concept overlap, kind mix (definition/method/metric/principle), ECTS, and external prerequisites.

    Concept overlap uses the same normalized word-match as
    suggest_substitution; an empty related_concepts list is a real, expected
    result for this dataset (see design-rationale doc) — it means the two
    courses cover disjoint material by name, not that the comparison failed.
    """
    g = graph_store.get_graph()
    a = g.course(_course_or_error(course_a))
    b = g.course(_course_or_error(course_b))

    pairs = g.related_concepts(a.code, b.code)
    related_a_names = {p[0] for p in pairs}
    related_b_names = {p[1] for p in pairs}

    def kind_dist(course) -> dict[str, int]:
        d: dict[str, int] = {}
        for c in course.concepts:
            d[c.kind] = d.get(c.kind, 0) + 1
        return d

    return CompareCoursesOutput(
        course_a=a.code, course_b=b.code, ects_a=a.ects, ects_b=b.ects,
        concept_count_a=len(a.concepts), concept_count_b=len(b.concepts),
        kind_distribution_a=kind_dist(a), kind_distribution_b=kind_dist(b),
        related_concepts=[RelatedConceptPair(concept_in_a=x, concept_in_b=y) for x, y in pairs],
        unique_to_a=[c.name for c in a.concepts if c.name not in related_a_names],
        unique_to_b=[c.name for c in b.concepts if c.name not in related_b_names],
        external_prerequisites_a=a.external_prerequisites,
        external_prerequisites_b=b.external_prerequisites,
    )


if __name__ == "__main__":
    server.run(transport="stdio")
