"""Artifacts: CSV, JSON, seed SQL, interactive HTML. No LLM, no DB connection."""
from __future__ import annotations
import csv
import json
from pathlib import Path

from .adapters import SourceFile
from .graph import ConceptGraph

HTML_TEMPLATE_NAME = "graph_template.html"


def _sql(v) -> str:
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def _write_csv(path: Path, rows: list[dict], cols: list[str]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    return len(rows)


def tables(g: ConceptGraph, files: list[SourceFile], unit_index: list[dict]) -> dict:
    courses = sorted({(f.course_code, f.course_title) for f in files})
    modules = sorted({(f"{u['course']}-M{u['module']}", u["course"], u["module"])
                      for u in unit_index})
    return {
        "courses": [{"course_code": c, "title": t} for c, t in courses],
        "modules": [{"module_code": m, "course_code": c, "ordinal": o}
                    for m, c, o in modules],
        "units": [{"unit_id": u["unit_id"], "module_code": f"{u['course']}-M{u['module']}",
                   "course_code": u["course"], "ordinal": u["unit"],
                   "n_files": u["n_files"], "chars": u["chars"]} for u in unit_index],
        "source_files": [{"rel_path": f.rel_path, "filename": f.filename,
                          "course_code": f.course_code, "unit_id": f.unit_id,
                          "asset_kind": f.asset_kind, "asset_ordinal": f.asset_ordinal,
                          "part_ordinal": f.part_ordinal, "bytes": f.bytes,
                          "sha256": f.sha256} for f in files],
        "concepts": [{"slug": c["slug"], "name": c["name"], "kind": c["kind"],
                      "difficulty": c["difficulty"], "domain": c["domain"],
                      "definition": c["definition"], "aliases": "|".join(c["aliases"]),
                      "courses": "|".join(c["courses"]), "units": "|".join(c["units"]),
                      "n_units": c["n_units"], "n_courses": c["n_courses"],
                      "degree": c["degree"], "occurrence_count": c["occurrence_count"],
                      "files": "|".join(c["files"])}
                     for c in sorted(g.concepts.values(), key=lambda x: x["slug"])],
        "concept_links": [{"src_slug": l["src"], "dst_slug": l["dst"], "type": l["type"],
                           "strength": l["strength"], "rationale": l["rationale"],
                           "origin": l.get("origin", "extracted"),
                           "cross_course": int(set(g.concepts[l["src"]]["courses"])
                                               != set(g.concepts[l["dst"]]["courses"]))}
                          for l in g.links],
        "concept_occurrences": [{"concept_slug": o["concept_slug"], "unit_id": o["unit_id"],
                                 "rel_path": o["rel_path"], "role": o["role"],
                                 "confidence": o["confidence"], "quote": o["quote"]}
                                for o in g.occurrences],
    }


def write_all(g: ConceptGraph, files: list[SourceFile], unit_index: list[dict],
              out_dir: Path, template_dir: Path | None = None) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    t = tables(g, files, unit_index)
    counts = {}
    for name, rows in t.items():
        if rows:
            counts[name] = _write_csv(out_dir / f"{name}.csv", rows, list(rows[0]))
    (out_dir / "concept_graph.json").write_text(
        json.dumps(t, ensure_ascii=False, indent=1), encoding="utf-8")

    # seed SQL against db/schema.sql
    L = ["-- generated by conceptgraph; run after schema.sql", "BEGIN;", "", "-- concepts"]
    for c in t["concepts"]:
        L.append("INSERT INTO concepts (slug,name,kind,definition,difficulty,domain,"
                 "provenance,confidence) VALUES ("
                 f"{_sql(c['slug'])},{_sql(c['name'])},{_sql(c['kind'])},"
                 f"{_sql(c['definition'])},{c['difficulty']},{_sql(c['domain'])},"
                 "'llm',0.8) ON CONFLICT (slug) DO NOTHING;")
    L.append("\n-- aliases")
    for c in t["concepts"]:
        for a in filter(None, c["aliases"].split("|")):
            L.append("INSERT INTO concept_aliases (concept_id,alias) SELECT id,"
                     f"{_sql(a)} FROM concepts WHERE slug={_sql(c['slug'])} "
                     "ON CONFLICT DO NOTHING;")
    L.append("\n-- links")
    for l in t["concept_links"]:
        L.append("INSERT INTO concept_links (src_concept_id,dst_concept_id,type,strength,"
                 "rationale,provenance) SELECT s.id,d.id,"
                 f"{_sql(l['type'])}::link_type,{l['strength']},{_sql(l['rationale'])},"
                 f"{_sql(l['origin'])} FROM concepts s, concepts d "
                 f"WHERE s.slug={_sql(l['src_slug'])} AND d.slug={_sql(l['dst_slug'])} "
                 "ON CONFLICT DO NOTHING;")
    L += ["", "COMMIT;"]
    (out_dir / "seed_concepts.sql").write_text("\n".join(L), encoding="utf-8")
    counts["seed_sql_statements"] = len(L)

    tpl = (template_dir or Path(__file__).parent) / HTML_TEMPLATE_NAME
    if tpl.exists():
        payload = {
            "nodes": [{"id": c["slug"], "n": c["name"], "k": c["kind"], "d": c["difficulty"],
                       "dom": c["domain"], "cs": c["courses"].split("|"),
                       "u": c["units"].split("|"), "deg": c["degree"],
                       "def": c["definition"], "f": [x for x in c["files"].split("|") if x],
                       "al": [x for x in c["aliases"].split("|") if x]}
                      for c in t["concepts"]],
            "links": [{"s": l["src_slug"], "t": l["dst_slug"], "ty": l["type"],
                       "w": l["strength"], "r": l["rationale"], "x": l["cross_course"],
                       "o": l["origin"]} for l in t["concept_links"]],
            "occ": {},
        }
        for o in t["concept_occurrences"]:
            payload["occ"].setdefault(o["concept_slug"], []).append(
                {"f": o["rel_path"], "r": o["role"], "q": o["quote"][:400]})
        html = tpl.read_text(encoding="utf-8").replace(
            "__DATA__", json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
        (out_dir / "concept_graph.html").write_text(html, encoding="utf-8")
        counts["html_bytes"] = len(html)
    return counts
